[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
  from = "/dev-api"
  to = "http://39.108.65.55:9000/dev-api"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
  
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"