[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "http://39.108.65.55:9000/dev-api"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS, HEAD"
    Access-Control-Allow-Headers = "content-type"