[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://your-frontend-domain.com"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS, HEAD"
    Access-Control-Allow-Headers = "content-type"